### ISSUE TITLE
endless shortcut_list errors in indigo event log

### ISSUE THREAD

**Issue by partymaster** [IndigoDomotics/Sonos#3]
Plugin seems to be working fine. Ran all the recommended terminal commands. Using Indigo 2023.1.

I get endless entries:

Action Collection Error         shortcut_list: failed to get shortcut list: 'Error: The operation couldn’t be completed. No such file or directory
'

Thanks.

**Comment by FlyingDiver** [comment]
Not a Sonos issue.  See https://forums.indigodomo.com/viewtopic.php?f=75&t=27492

**Comment by partymaster** [comment]
correct, sorry about that!
